{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kangalis.serviceAccountName" . }}
  labels:
    {{- include "kangalis.labels" . | nindent 4 }}
{{- end }}
