"""cpe_matches table for offline matching

Revision ID: 1a700bb42ab9
Revises: a1b2c3d4e5f6
Create Date: 2026-06-05 11:29:40.892965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a700bb42ab9'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpe_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(length=30), nullable=False),
    sa.Column('part', sa.String(length=2), nullable=False),
    sa.Column('vendor', sa.String(length=128), nullable=False),
    sa.Column('product', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=False),
    sa.Column('vulnerable', sa.Boolean(), nullable=False),
    sa.Column('version_start_including', sa.String(length=64), nullable=True),
    sa.Column('version_start_excluding', sa.String(length=64), nullable=True),
    sa.Column('version_end_including', sa.String(length=64), nullable=True),
    sa.Column('version_end_excluding', sa.String(length=64), nullable=True),
    sa.Column('criteria', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cpe_matches_cve_id'), 'cpe_matches', ['cve_id'], unique=False)
    op.create_index('ix_cpe_vendor_product', 'cpe_matches', ['vendor', 'product'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cpe_vendor_product', table_name='cpe_matches')
    op.drop_index(op.f('ix_cpe_matches_cve_id'), table_name='cpe_matches')
    op.drop_table('cpe_matches')
    # ### end Alembic commands ###
