"""cve table

Revision ID: 50ac1e4723ec
Revises: 125a2cd8f667
Create Date: 2026-06-04 19:46:53.534392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ac1e4723ec'
down_revision: Union[str, Sequence[str], None] = '125a2cd8f667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cves',
    sa.Column('cve_id', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', 'info', name='severity', native_enum=False, length=10), nullable=True),
    sa.Column('references', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('cve_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cves')
    # ### end Alembic commands ###
