"""scheduled scans

Revision ID: af93c05a857c
Revises: c22d9b1f677c
Create Date: 2026-06-04 20:49:50.244218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af93c05a857c'
down_revision: Union[str, Sequence[str], None] = 'c22d9b1f677c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_type', sa.Enum('network', 'web', 'sca', 'hardening', name='scantype', native_enum=False, length=20), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_scans')
    # ### end Alembic commands ###
