"""Yerleşik (varsayılan) kelime listeleri — zengin EN/TR içerik.

Bu listeler ``seed_builtin_wordlists`` ile DB'ye yerleşik (is_builtin) olarak eklenir;
Kelime Listeleri sayfasında salt-okunur görüntülenir ve taramalarda seçilebilir.
İçerik yetkili-iç-pentest amaçlı yaygın zayıf/varsayılan değerlerdir.

(EN) = İngilizce/uluslararası yaygın · (TR) = Türkçe'ye özgü (kulüp/şehir/isim/klavye kalıpları).
"""

from __future__ import annotations

from cybersectool.core.models import WordlistKind

# --- Kullanıcı adları ---
USERNAMES_EN: tuple[str, ...] = (
    "root",
    "admin",
    "administrator",
    "user",
    "test",
    "guest",
    "oracle",
    "postgres",
    "mysql",
    "ubuntu",
    "ftp",
    "ftpuser",
    "operator",
    "manager",
    "service",
    "sa",
    "www-data",
    "www",
    "support",
    "backup",
    "tomcat",
    "jenkins",
    "git",
    "deploy",
    "devops",
    "nagios",
    "zabbix",
    "elastic",
    "kibana",
    "grafana",
    "redis",
    "mongodb",
    "vagrant",
    "pi",
    "centos",
    "debian",
    "demo",
    "info",
    "webmaster",
    "sysadmin",
)

USERNAMES_TR: tuple[str, ...] = (
    "yonetici",
    "kullanici",
    "misafir",
    "destek",
    "admin",
    "yonetim",
    "personel",
    "muhasebe",
    "satis",
    "depo",
    "bilgi",
    "iletisim",
    "ahmet",
    "mehmet",
    "mustafa",
    "ali",
    "huseyin",
    "hasan",
    "ibrahim",
    "ayse",
    "fatma",
    "emine",
    "hatice",
    "zeynep",
    "test",
    "deneme",
    "operator",
    "sistem",
    "guvenlik",
    "teknik",
)

# --- Parolalar (yaygın zayıf/varsayılan) ---
PASSWORDS_EN: tuple[str, ...] = (
    "123456",
    "password",
    "12345678",
    "qwerty",
    "123456789",
    "12345",
    "1234",
    "111111",
    "1234567",
    "dragon",
    "123123",
    "baseball",
    "abc123",
    "football",
    "monkey",
    "letmein",
    "shadow",
    "master",
    "666666",
    "qwertyuiop",
    "123321",
    "mustang",
    "1234567890",
    "michael",
    "654321",
    "superman",
    "1qaz2wsx",
    "7777777",
    "121212",
    "000000",
    "qazwsx",
    "123qwe",
    "killer",
    "trustno1",
    "jordan",
    "jennifer",
    "zxcvbnm",
    "asdfgh",
    "hunter",
    "buster",
    "soccer",
    "harley",
    "batman",
    "andrew",
    "tigger",
    "sunshine",
    "iloveyou",
    "2000",
    "charlie",
    "robert",
    "thomas",
    "hockey",
    "ranger",
    "daniel",
    "starwars",
    "klaster",
    "112233",
    "george",
    "computer",
    "michelle",
    "jessica",
    "pepper",
    "1111",
    "zxcvbn",
    "555555",
    "11111111",
    "131313",
    "freedom",
    "777777",
    "pass",
    "maggie",
    "password1",
    "admin",
    "root",
    "toor",
    "changeme",
    "welcome",
    "passw0rd",
    "P@ssw0rd",
    "secret",
    "default",
    # Karmaşıklık politikasını KARŞILAYAN ama zayıf kalıplar (büyük+küçük+rakam, ≥8 hane) —
    # kurumsal ortamlarda EN sık görülenler; politika zorunluluğu bunları popüler yapar.
    "Aa123456",
    "Aa1234567",
    "Aa12345678",
    "Aa123456!",
    "Aa@123456",
    "Abcd1234",
    "Abc@1234",
    "Abcd@1234",
    "Password1",
    "Password1!",
    "Password123",
    "Password@123",
    "Passw0rd1",
    "Passw0rd!",
    "P@ssw0rd1",
    "P@ssword1",
    "Welcome1",
    "Welcome1!",
    "Welcome123",
    "Welcome@123",
    "Admin@123",
    "Admin123!",
    "Admin@1234",
    "Root@123",
    "Qwerty123",
    "Qwerty123!",
    "Summer2024",
    "Winter2024",
    "Spring2024",
    "Autumn2024",
)

PASSWORDS_TR: tuple[str, ...] = (
    "123456",
    "sifre",
    "parola",
    "123456789",
    "qwe123",
    "asd123",
    "1234567",
    "12345678",
    "deneme",
    "merhaba",
    "ankara",
    "istanbul",
    "izmir",
    "bursa",
    "trabzon",
    "adana",
    "galatasaray",
    "fenerbahce",
    "besiktas",
    "trabzonspor",
    "cimbom",
    "fener",
    "1907",
    "1903",
    "1905",
    "gsgsgs",
    "fbfbfb",
    "kartal",
    "aslan",
    "kanarya",
    "sampiyon",
    "turkiye",
    "mustafa",
    "mehmet1",
    "ahmet123",
    "ali1234",
    "ayse1234",
    "fatma123",
    "selam",
    "sevgi",
    "askim",
    "canim",
    "bebek",
    "melek",
    "kibar",
    "yildiz",
    "gizli",
    "deneme123",
    "qwe123tr",
    # Karmaşıklık politikasını karşılayan ama zayıf — Türkçe kurumsal ortam kalıpları.
    "Sifre123",
    "Sifre@123",
    "Sifre1234",
    "Sifre123!",
    "Parola123",
    "Parola@123",
    "Ankara06",
    "Istanbul34",
    "Izmir35",
    "Galatasaray1",
    "Fenerbahce1",
    "Besiktas1",
    "Trabzon61",
    "Turkiye1",
    "Merhaba123",
    "Deneme123!",
    "Sifrem123",
    "Aa123456",
)

# --- Web dizinleri ---
WEB_DIRS_TR: tuple[str, ...] = (
    "yonetim",
    "yonetici",
    "giris",
    "cikis",
    "kullanici",
    "kullanicilar",
    "uye",
    "uyeler",
    "uyelik",
    "kayit",
    "parola",
    "sifre",
    "ayarlar",
    "panel",
    "kontrol",
    "denetim",
    "yedek",
    "yedekler",
    "yukle",
    "indir",
    "dosya",
    "dosyalar",
    "belge",
    "belgeler",
    "resim",
    "resimler",
    "gorsel",
    "medya",
    "rapor",
    "raporlar",
    "istatistik",
    "log",
    "kayitlar",
    "urun",
    "urunler",
    "kategori",
    "siparis",
    "siparisler",
    "sepet",
    "odeme",
    "fatura",
    "musteri",
    "musteriler",
    "personel",
    "calisanlar",
    "duyuru",
    "duyurular",
    "haber",
    "haberler",
    "iletisim",
    "hakkimizda",
    "destek",
    "yardim",
    "sss",
    "arama",
    "test",
    "gecici",
    "eski",
    "yeni",
    "admin",
    "site",
)

# --- SMB paylaşımları (protokol-standart; dil-bağımsız) ---
SMB_SHARES: tuple[str, ...] = (
    "ADMIN$",
    "C$",
    "D$",
    "E$",
    "F$",
    "IPC$",
    "public",
    "Public",
    "share",
    "Share",
    "shared",
    "Shared",
    "data",
    "Data",
    "backup",
    "Backup",
    "backups",
    "users",
    "Users",
    "home",
    "homes",
    "files",
    "Files",
    "tmp",
    "temp",
    "wwwroot",
    "www",
    "web",
    "netlogon",
    "NETLOGON",
    "sysvol",
    "SYSVOL",
    "print$",
    "scans",
    "media",
    "docs",
    "documents",
    "yedek",
    "ortak",
    "muhasebe",
)


def generate_policy_passwords() -> list[str]:
    """Parola politikası KARŞILAYAN ama tahmin edilebilir parolalar üretir (deterministik).

    Kalıp: <Büyük-harfli taban> + <rakam> + opsiyonel son özel karakter (``!``/``.``).
    Böylece her parola en az 1 büyük + 1 küçük harf + 1 rakam içerir ve ~8-14 hane olur —
    LDAP/AD ortamlarında karmaşıklık zorunluluğu yüzünden EN sık görülen 'spray' adayları.
    Yeni taban/rakam eklemek listeyi otomatik büyütür (açılışta reconcile tazeler).
    """
    bases = (
        "Password",
        "Welcome",
        "Summer",
        "Winter",
        "Spring",
        "Autumn",
        "Company",
        "Qwerty",
        "Admin",
        "Master",
        "Changeme",
        "Letmein",
        "Sifre",
        "Parola",
        "Istanbul",
        "Ankara",
        "Izmir",
        "Galatasaray",
        "Fenerbahce",
        "Besiktas",
        "Trabzon",
        "Turkiye",
        "Merhaba",
        "Deneme",
    )
    digits = ("1", "12", "123", "2024", "2025")
    trailers = ("", "!", ".")
    seen: set[str] = set()
    out: list[str] = []
    for base in bases:
        for d in digits:
            for trailer in trailers:
                pw = f"{base}{d}{trailer}"
                if 8 <= len(pw) <= 14 and pw not in seen:
                    seen.add(pw)
                    out.append(pw)
    # Klavye + rakam ailesi (Aa123456 vb.) — politika-uyumlu yaygın sabitler.
    for extra in (
        "Aa123456",
        "Aa123456!",
        "Aa1234567!",
        "Aa12345678",
        "Abcd1234!",
        "Abcd@1234",
        "Qwerty123!",
        "Asdf1234!",
        "Zxcvbn1!",
        "1qaz2wsX!",
    ):
        if extra not in seen:
            seen.add(extra)
            out.append(extra)
    return out


# Yaygın Türkçe ad+soyad çiftleri — AD kullanıcı adı üretimi için (gerçekçi tam isimler).
_FULL_NAMES: tuple[tuple[str, str], ...] = (
    ("ahmet", "yilmaz"),
    ("mehmet", "kaya"),
    ("mustafa", "demir"),
    ("ali", "sahin"),
    ("huseyin", "celik"),
    ("hasan", "yildiz"),
    ("ibrahim", "yildirim"),
    ("ismail", "ozturk"),
    ("osman", "aydin"),
    ("yusuf", "ozdemir"),
    ("murat", "arslan"),
    ("omer", "dogan"),
    ("emre", "kilic"),
    ("burak", "aslan"),
    ("can", "cetin"),
    ("deniz", "kara"),
    ("kemal", "koc"),
    ("suleyman", "kurt"),
    ("kadir", "ozkan"),
    ("ramazan", "simsek"),
    ("ayse", "yilmaz"),
    ("fatma", "kaya"),
    ("emine", "demir"),
    ("hatice", "sahin"),
    ("zeynep", "celik"),
    ("elif", "yildiz"),
    ("meryem", "yildirim"),
    ("ozlem", "ozturk"),
    ("hulya", "aydin"),
    ("sevim", "ozdemir"),
)


def generate_usernames() -> list[str]:
    """Yaygın ad+soyad çiftlerinden AD/LDAP kullanıcı adı kalıpları üretir (deterministik).

    Kalıplar: ``flast`` · ``first.last`` · ``f.last`` · ``firstlast`` · ``first_last`` ·
    ``first`` · ``firstl``. Kurumlarda en sık kullanılan kullanıcı-adı biçimlerini kapsar →
    AD/LDAP brute/spray için güçlü başlangıç listesi. Sıra korunarak tekilleştirilir.

    Üretim mantığı ``core.wordlist_generators.generate_usernames`` içindedir (UI'daki
    interaktif üretici ile TEK kaynak); burada yerleşik ``_FULL_NAMES`` ile çağrılır.
    """
    from cybersectool.core.wordlist_generators import generate_usernames as _gen

    return _gen(_FULL_NAMES)


def builtin_wordlists() -> list[tuple[str, WordlistKind, list[str]]]:
    """Kanonik yerleşik liste kümesi: (ad, tür, satırlar). seed reconcile bunu kullanır."""
    # web_dir (EN): tarayıcının gömülü DIRSCAN_WORDLIST'i + SNMP gömülü topluluk listesi
    # (lazy import — core→scanners bağımlılığını modül yükleme anında kurmamak için).
    from cybersectool.core.snmp_wordlist import SNMP_COMMUNITY_WORDLIST
    from cybersectool.scanners.web import DIRSCAN_WORDLIST

    return [
        ("Web dizinleri (EN)", WordlistKind.web_dir, list(DIRSCAN_WORDLIST)),
        ("Web dizinleri (TR)", WordlistKind.web_dir, list(WEB_DIRS_TR)),
        ("Kullanıcı adları (EN)", WordlistKind.username, list(USERNAMES_EN)),
        ("Kullanıcı adları (TR)", WordlistKind.username, list(USERNAMES_TR)),
        ("Üretilen kullanıcı adları (AD)", WordlistKind.username, generate_usernames()),
        ("Zayıf parolalar (EN)", WordlistKind.password, list(PASSWORDS_EN)),
        ("Zayıf parolalar (TR)", WordlistKind.password, list(PASSWORDS_TR)),
        ("Politika-uyumlu parolalar (spray)", WordlistKind.password, generate_policy_passwords()),
        ("SMB paylaşımları", WordlistKind.smb_share, list(SMB_SHARES)),
        ("SNMP toplulukları", WordlistKind.snmp_community, list(SNMP_COMMUNITY_WORDLIST)),
    ]
